# Generated by Django 3.1.5 on 2021-01-28 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
