# Generated by Django 3.1.5 on 2021-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('continent', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('property_image', models.CharField(max_length=300)),
                ('is_available', models.BooleanField(default=False)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
    ]
