# Generated by Django 3.1.5 on 2021-01-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210126_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.CharField(max_length=500),
        ),
    ]
