# Generated by Django 3.1.5 on 2021-01-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210127_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
