# Generated by Django 3.1.5 on 2021-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_types', '0001_initial'),
        ('properties', '0007_auto_20210127_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='types',
            field=models.ManyToManyField(related_name='properties', to='property_types.PropertyType'),
        ),
    ]
