# Generated by Django 3.1.5 on 2021-01-27 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0009_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_property', to=settings.AUTH_USER_MODEL),
        ),
    ]
