# Generated by Django 3.1.5 on 2021-01-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_property_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('offered_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_property', to='properties.property')),
                ('requested_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_property', to='properties.property')),
            ],
        ),
    ]
