# Generated by Django 3.1.5 on 2021-01-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_types'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='requested_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property'),
        ),
    ]
