# Generated by Django 3.1.5 on 2021-02-01 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_auto_20210127_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, related_name='posted_offers', to='jwt_auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.TextField(max_length=300),
        ),
    ]
